config/routes.rb
Cairn::Application.routes.draw do
  devise_for :admin_users, :path => "_admin", controllers: { sessions: "admin/sessions" }
  devise_for :users, controllers: { registrations: "users/registrations" }

  scope "_admin", :as => "admin" do
    root :to => "admin#index"
    resources :change_requests, :module => "admin"
    put 'change_requests/:id/approve' => 'admin/change_requests#approve', :as => 'change_request_approve'
  end

  resources :organizations
  post '/organizations/:id/set_realm' => 'organizations#set_realm', :as => 'set_organization_realm'

  resources :atlases, :path => 'organizations/:organization_id/atlases', :as => 'atlases'

  root 'page#index'
end

app/controllers/atlases_controller.rb
class AtlasesController < ApplicationController
	before_filter :authenticate_user!
	before_filter :get_organization_for_user

	def edit
		get_atlas
		@tag_types = @organization.tag_types
		@tag = (@atlas.realm || Tag.new)
		@realm = @organization.realm
	end

	def new
		@atlas = Atlas.new(:organization_id => @organization.id)
		@tag_types = @organization.tag_types
		@tag = Tag.new
		@realm = @organization.realm
	end

	def show
		get_atlas
	end

	def set_realm
		realm = (@atlas.realm || Tag.new(:organization_id => @organization.id))
		realm_attrs = tag_params.merge({:name => @atlas.name})
		ok = realm.update_attributes(realm_attrs) && 
			@atlas.update_attributes(:realm_id => realm.id)
		return ok
	end

	def update
		get_atlas
		realm_ok = (atlas_params[:geo_filter] && atlas_params[:geo_filter].to_s != '0') ? set_realm : true
		ok = realm_ok && @atlas.update_attributes(atlas_params)
		flash[:notice] = ok ? 'Updated atlas' : 'Failed to update'
		return redirect_to atlas_path(@organization.id, @atlas.id)
	end

	def create
		@atlas = Atlas.new(:organization_id => @organization.id)
		realm_ok = nil
		atlas_ok = @atlas.update_attributes(atlas_params)
		if atlas_ok
			realm_ok = (atlas_params[:geo_filter] && atlas_params[:geo_filter].to_s != '0') ? set_realm : true
		end
		if atlas_ok && realm_ok
			flash[:notice] = 'Successfully created atlas'
			return redirect_to organization_path(@organization.id)
		else
			flash[:notice] = 'Failed to create atlas'
			return redirect_to new_atlas_path(@organization.id) 
		end
	end

	private

	def get_atlas
		@atlas = Atlas.find(params[:id])
		return render_404 unless @atlas
	end

	def atlas_params
		params.require(:atlas).permit(:name, :geo_filter, :realm_attributes => [:id])
	end

	def tag_params
		params.require(:tag).permit(:name, :center, :radius, :tag_type_id, :organization_id)
	end
end

app/views/atlases/_form.haml
-# locals you need to define when rendering this partial:
-# 'tag': the actual tag you are assigning values to
-# 'tag_types': the tag_types available to the parent organization or atlas
-# 'organization': the tag's parent organization
-# 'form_header': the message you want at the top of the form
-# 'realm': the realm of the parent atlas or organization--the geographical area on which we will focus the map
-# 'tag_is_realm': whether the tag we are using will be used as a relam for an atlas or organization
.row
	%h2.col-md-10.col-sm-10= form_header
.row
	.col-md-6.col-sm-6#map-domain
		#map-canvas
	.col-md-3.col-sm-3
		= semantic_form_for atlas, :url => (atlas.new_record? ? atlases_path : atlas_path(organization.id, atlas.id)), :method => (atlas.new_record? ? 'post' : 'put') do |f|
			=f.inputs do
				=f.input :name, :label => false, :placeholder => 'Name'
				%li.label Use geographic filter?
				=f.input :geo_filter, :as => :boolean, :label => false
			=f.inputs do
				=f.semantic_fields_for tag do |r|
					=render :partial => '/tags/inputs', :locals => {:f => r, :organization => organization, :tag_types => tag_types, :realm => (realm || nil), :tag => tag, :tag_is_realm => true}
				=f.submit :class => 'btn btn-sm btn-primary'

app/views/atlases/edit.html.haml
.row
	.col-md-10
		%h1= @organization.name
.row
	.col-md-2
	.col-md-10
		%h2= @atlas.name
-if flash[:notice]
	.row
		%p.text-warning= flash[:notice]
=render :partial => "/atlases/form", :locals => {:atlas => @atlas, :tag_types => @tag_types, :organization => @organization, :form_header => 'Define your atlas', :realm => @realm, :tag => @tag}

app/views/atlases/new.html.haml
.row
	.col-md-10
		%h1= @organization.name
.row
	.col-md-2
	.col-md-10
		%h2 New Atlas
-if flash[:notice]
	.row
		%p.text-warning= flash[:notice]
=render :partial => "/atlases/form", :locals => {:atlas => @atlas, :tag_types => @tag_types, :organization => @organization, :form_header => 'Define your atlas', :realm => @realm, :tag => @tag}

app/views/atlases/show.html.haml
.row
	.col-md-10
		%h1= @organization.name
.row
	.col-md-2
	.col-md-10
		%h2= @atlas.name
-if flash[:notice]
	.row
		%p.text-warning= flash[:notice]