config/routes.rb
Cairn::Application.routes.draw do
  devise_for :admin_users, :path => "_admin", controllers: { sessions: "admin/sessions" }
  devise_for :users, controllers: { registrations: "users/registrations" }

  scope "_admin", :as => "admin" do
    root :to => "admin#index"
    resources :change_requests, :module => "admin"
    put 'change_requests/:id/approve' => 'admin/change_requests#approve', :as => 'change_request_approve'
  end

  resources :organizations
  post '/organizations/:id/set_realm' => 'organizations#set_realm', :as => 'set_organization_realm'

  resources :atlases, :path => 'organizations/:organization_id/atlases', :as => 'atlases'

  root 'page#index'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	before_save :set_circle
	belongs_to :tag_typeexi

	scope :intersects_geometry, -> (geo) {
		where(%{
			ST_Intersects(
				tags.shape,
				ST_GeographyFromText('SRID=4326;%s')
			)
		} % [geo])
	}

	# Tag.declare_get_relevance must be run before this scope is used
	# TODO: Write test to ensure this is returning in descending order
	scope :sort_by_relevance, -> (geo) {
		order(%{get_relevance(ST_GeographyFromText('SRID=4326;%s'), tags.shape) DESC} % [geo])
	}

	# returns an array of all tags which intersect current tag, sorted in order of 
	def relevant_tags
		Tag.declare_get_relevance
		Tag.intersects_geometry(self.shape).sort_by_relevance(self.shape).to_a.reject{ |x| 
			x.id == self.id
		}
	end

	# Must be run before any SQL query using the get_relevance function
	def self.declare_get_relevance
		ActiveRecord::Base.connection.execute("
			DROP FUNCTION IF EXISTS get_relevance(geoOne GEOGRAPHY, geoTwo GEOGRAPHY);
			CREATE FUNCTION get_relevance(geoOne GEOGRAPHY, geoTwo GEOGRAPHY) RETURNS FLOAT AS $$
			DECLARE
				sharedArea FLOAT;
				relevanceScore FLOAT;
			BEGIN
				sharedArea := (st_area(ST_Intersection(geoOne, geoTwo)));
				relevanceScore := (sharedArea * sharedArea) / (st_area(geoOne) * st_area(geoTwo));
				RETURN relevanceScore;
			END;
			$$ LANGUAGE plpgsql;
		");
	end

	def set_circle
		ok = true
		if self.center == nil
			ok = false
			self.errors.add(:center, "Must have center point")
		end
		if self.radius == nil
			ok = false
			self.errors.add(:radius, "Must have radius")
		end
		self.shape = self.center.buffer(self.radius) if ok
		return ok
	end

	def deg_per_met
		r = 6371000
		latrad = (90 - self.center.y).abs * (2*Math::PI/360) # Converts latitudinal degrees into radians for the sake of sake of Ruby's sin function.
		rprime = r * Math.sin(latrad) # Using SOHCAHTOA to get the horizontal cross-sectional radius of the earth at the user's latitude.
		return 360 / (rprime*2*Math::PI) # Takes this radius and uses it to get the cross-sectional circumference at that point in meters
		# and return 360 degrees by this circumferences to get degrees per meter.
	end

end

app/models/tag_type.rb
class TagType < ActiveRecord::Base
	has_many :tags
	validates_presence_of :name
	validates :radius, :presence => true, :numericality => true

	def self.private
		TagType.where("organization_id IS NOT NULL")
	end
end

app/views/tags/_form.html.haml
.row
	%h2.col-md-10.col-sm-10= form_header
.row
	.col-md-6.col-sm-6#map-domain
		#map-canvas
	.col-md-3.col-sm-3
		= semantic_form_for tag, :url => set_organization_realm_path(organization.id) do |f|
			=f.inputs do
				=render :partial => '/tags/inputs', :locals => {:f => f, :organization => organization, :tag_types => tag_types, :realm => realm, :tag => tag, :tag_is_realm => tag_is_realm}
				=f.submit :class => 'btn btn-sm btn-primary'

app/views/tags/_inputs.html.haml
-# locals you need to define when rendering this partial:
-# 'f': the form variable passed through the semantic_form_for block
-# 'tag': the actual tag you are assigning values to
-# 'tag_types': the tag_types available to the parent organization or atlas
-# 'organization': the tag's parent organization
-# 'realm': the realm of the parent atlas or organization--the geographical area on which we will focus the map
-# 'tag_is_realm': whether the tag we are using will be used as a relam for an atlas or organization

/ =content_for :head do
=content_for :end_body do
	= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyAYQDEv0bZNaE9pQEZXOYQbaSVQ2grJ8fg&sensor=true"
	= javascript_include_tag 'views/tags/form'
-if !tag_is_realm # No name input if we're creating a realm for an atlas or organization
	=f.input :name, :label => false, :placeholder => 'Name', :input_html => {:name => 'tag[name]'}
=f.input :radius, :label => false, :placeholder => 'Radius (meters)', :input_html => {:id => 'tag_radius', :name => 'tag[radius]'}
=f.input :center, :as => :hidden, :input_html => {:id => 'tag_center', :name => 'tag[center]'}
=f.input :organization_id, :as => :hidden, :input_html => {:name => 'tag[organization_id]'}
=f.input :tag_type_id, :as => :select, :collection => tag_types.map{|t| [t.name, t.id]}, :label => false, :include_blank => true, :prompt => 'Select Type', :input_html => {:id => 'tag_tag_type_id', :name => 'tag[tag_type_id]'}

-# The below inputs are not sent on submit but rather store values for form.js
%input#hidden_tag_lat{:type => 'hidden', :value => ((tag && tag.center) ? tag.center.y : nil)}
%input#hidden_tag_lng{:type => 'hidden', :value => ((tag && tag.center) ? tag.center.x : nil)}
%input#hidden_tag_radius_degrees{:type => 'hidden', :value => ((tag && tag.radius && tag.center) ? (tag.radius * tag.deg_per_met) : nil)}

-tag_types.each do |t|
	%input{:id => "tag_type_#{t.id.to_s}", :value => t.radius, :type => 'hidden'}
%input#hidden_realm_radius{:type => 'hidden', :value => (realm ? (realm.radius * realm.deg_per_met) : nil)}
%input#hidden_realm_lat{:type => 'hidden', :value => ((realm && realm.center) ? realm.center.y : nil)}
%input#hidden_realm_lng{:type => 'hidden', :value => ((realm && realm.center) ? realm.center.x : nil)}