config/routes.rb
Cairn::Application.routes.draw do
  devise_for :admin_users, :path => "_admin", controllers: { sessions: "admin/sessions" }
  devise_for :users, controllers: { registrations: "users/registrations" }

  scope "_admin", :as => "admin" do
    root :to => "admin#index"
    resources :change_requests, :module => "admin"
    put 'change_requests/:id/approve' => 'admin/change_requests#approve', :as => 'change_request_approve'
  end

  resources :organizations
  post '/organizations/:id/set_realm' => 'organizations#set_realm', :as => 'set_organization_realm'

  resources :atlases, :path => 'organizations/:organization_id/atlases', :as => 'atlases'

  root 'page#index'
end

app/models/change_request.rb
class ChangeRequest < ActiveRecord::Base
	belongs_to :user
	belongs_to :tag

	@@tag_attributes = ['center', 'radius', 'shape', 'name']

	# Takes in a distance in meters. Remember, feed in the x-coordinate first, then the y.
	scope :within_distance, -> (longitude, latitude, distance) {
		where(%{
			ST_DWithin(
				change_requests.center,
				ST_GeographyFromText('SRID=4326;POINT(%f %f)'),
				%d
			)
		} % [longitude, latitude, distance])
	}

	scope :unresolved, -> {where('resolved IS NOT TRUE')}

	def approve
		ok = self.tag.update_attributes(self.change_attributes)
	end

	def change_attributes
		self.attributes.select{|k,v| ( @@tag_attributes.include?(k.to_s) && !v.nil? )}
	end
end

app/controllers/admin/change_requests_controller.rb
class Admin::ChangeRequestsController < AdminController
	before_filter :get_change_request

	def index
		@change_requests = ChangeRequest.unresolved
	end

	def edit
		unless @change_request
			return render_404
		end
	end

	def approve
		unless @change_request
			return render_500
		end
		@change_request.approve
		redirect_to admin_change_requests_path
	end

	def get_change_request
		@change_request = ChangeRequest.where(:id => params[:id]).last
	end
end

app/views/admin/change_requests/edit.html.haml
%p hello
= form_tag admin_change_request_approve_path(@change_request.id), :method => :put do
	=submit_tag "Approve Change Request", :class => 'btn'

app/views/admin/change_requests/index.html.haml
%h1#index-title Change Requests
%table
%thead
	%tr
		%td Tag
		%td User
		%td Created
		%td View

%tbody
	- @change_requests.each do |cr|
		%tr.change-request
			%td= cr.tag.name
			%td= cr.user.name
			%td= cr.created_at
			%td
				=link_to 'Edit', edit_admin_change_request_path(cr.id), :class => 'view'